import AnimatedSection, { AnimatedItem } from '../components/AnimatedSection.jsx'
import SiteFooter from '../components/SiteFooter.jsx'

const updatedAt = 'June 23, 2026'

function PrivacyPolicyPage() {
  return (
    <div className="app-shell">
      <main className="info-page legal-page">
        <AnimatedSection className="info-hero">
          <AnimatedItem as="p" className="eyebrow">Privacy</AnimatedItem>
          <AnimatedItem as="h1">Privacy Policy</AnimatedItem>
          <AnimatedItem as="p">
            This policy explains what FIEK Hub collects, why it is used, and
            what choices you have. Last updated: {updatedAt}.
          </AnimatedItem>
        </AnimatedSection>

        <AnimatedSection className="legal-content" item>
          <h2>1. Who operates FIEK Hub</h2>
          <p>
            FIEK Hub is an independent student project. It is not currently an
            official University of Prishtina or FIEK service. The app is built
            for student account access, setup, and study materials.
          </p>

          <h2>2. Data we collect</h2>
          <p>Depending on how you use the app, we may process:</p>
          <ul>
            <li>Account data: email address, authentication identifiers, and password credentials handled by Supabase Auth.</li>
            <li>
              Profile data: full name, department, student year, group, role,
              and profile visibility setting.
            </li>
            <li>Contact data: name, email, category, subject, and message submitted through the contact form.</li>
            <li>Technical data: basic logs and security events generated by Supabase, Vite hosting, or browser requests.</li>
          </ul>

          <h2>3. Why we use data</h2>
          <p>We use data to create accounts, protect access, complete student setup, show relevant app sections, respond to contact messages, prevent abuse, and maintain the service.</p>

          <h2>4. Legal basis and privacy principles</h2>
          <p>
            The policy is written to follow practical privacy principles from
            Kosovo Law No. 06/L-082 on Protection of Personal Data and European
            data-protection expectations, including transparency, data
            minimization, security, and user rights.
          </p>

          <h2>5. Service providers</h2>
          <p>
            FIEK Hub uses Supabase for authentication and database storage.
            Supabase processes account and contact data needed to operate the
            app. PDF materials are served as public static files.
          </p>

          <h2>6. What we do not collect</h2>
          <p>
            We do not intentionally collect payment details, government ID
            numbers, health data, or phone numbers. Phone-number recovery was
            removed from the app.
          </p>

          <h2>7. Retention</h2>
          <p>
            Account data is kept while your account exists. Contact messages are
            kept only as long as needed to review and respond. Materials viewed
            inside the app are not used to build a behavioral profile.
          </p>

          <h2>8. Your choices</h2>
          <p>
            You can update your profile and password from Account settings. You
            can request correction or deletion of contact messages or account
            data through the Contact page.
          </p>

          <h2>9. Security</h2>
          <p>
            The app relies on Supabase Auth for authentication and uses row-level
            security for contact submissions. No web app can guarantee perfect
            security, so avoid submitting sensitive information through the
            contact form.
          </p>

          <h2>10. Changes</h2>
          <p>
            This policy may be updated as the app grows. Material changes should
            be reflected on this page with a new update date.
          </p>
        </AnimatedSection>

        <SiteFooter />
      </main>
    </div>
  )
}

export default PrivacyPolicyPage
